{
 "title": "HealthChecker",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "URL Status",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sample_external_url_up", "legendFormat": "{{ url }}" }
   ]
  },
  {
   "title": "URL Response ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sample_external_url_ms", "legendFormat": "{{ url }}" }
   ]
  },
  {
   "title": "Request Details",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sample_external_url_connect_time",
     "legendFormat": "Connect Time {{ url }}"
    },
    { "expr": "sample_external_url_dns", "legendFormat": "DNS Lookup {{ url }}" },
    { "expr": "sample_external_url_first_byte", "legendFormat": "First Byte {{ url }}" }
   ]
  },
  {
   "title": "Container Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{app_kubernetes_io_name=\"healthchecker-go\"}"
    }
   ]
  }
 ]
}